HH/HH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from hhapp.api_views import EmployerViewSet


router = routers.DefaultRouter()
router.register(r'employeries', EmployerViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hhapp.urls', namespace='hh')),
    path('users/', include('userapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

HH/hhapp/urls.py
from django.urls import path
from hhapp import views


app_name = 'hhapp'

urlpatterns = [
    path('', views.start, name='index'),
    path('form/', views.form, name='form'),
    path('result/', views.result, name='result'),
    path('ws-list/', views.WSList.as_view(), name='ws_list'),
    path('area-list/', views.AreaList.as_view(), name='area_list'),
    path('area-detail/<int:pk>/', views.AreaDetail.as_view(), name='area_detail'),
    path('area-create/', views.AreaCreate.as_view(), name='area_create'),
    path('area-update/<int:pk>/', views.AreaUpdateView.as_view(), name='area_update'),
    path('area-delete/<int:pk>/', views.AreaDeleteView.as_view(), name='area_delete')
]

HH/hhapp/models.py
from datetime import datetime, timedelta

from django.db import models
from django.db.models import Model, CharField, TextField, DateTimeField, ForeignKey
from django.db.models import ManyToManyField, URLField, FloatField, IntegerField


class Area(Model):
    name = CharField(max_length=30, verbose_name='Регион')
    ind_hh = IntegerField(verbose_name='Номер HH', blank=True, null=True, default=0)
    ind_zarp = IntegerField(verbose_name='Номер Zarplata', blank=True, null=True, default=0)
    ind_super = IntegerField(verbose_name='Номер SuperJob', blank=True, null=True, default=0)
    
    def __str__(self):
        return self.name

    def __eq__(self, other):
        if isinstance(self, type(other)) and self.name == other.name and self.ind_hh == other.ind_hh\
                and self.ind_zarp == other.ind_zarp:
                # and self.ind_zarp == other.ind_zarp and self.ind_super == other.ind_super:
            return True
        return False

    class Meta:
        verbose_name = 'Название региона'
        verbose_name_plural = 'Регионы'


class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        d = datetime.now() - timedelta(days=1)
        return all_objects.filter(published__gte=d)


class IsActiveMixin(Model):
    objects = models.Manager()
    active_objects = ActiveManager()

    class Meta:
        abstract = True


class Employer(Model):
    name = CharField(max_length=30)
    ind = IntegerField(blank=True, null=True)
    link = URLField(blank=True, null=True)


class Schedule(Model):
    name = CharField(max_length=20)

    def __str__(self):
        return self.name


class Word(Model):
    word = CharField(max_length=30, verbose_name='Запрос')
    count = IntegerField(verbose_name='Количество')
    up = FloatField(verbose_name="Верхняя граница")
    down = FloatField(verbose_name='Нижняя граница')

    def __str__(self):
        return self.word

    class Meta:
        verbose_name = 'Текст запроса'
        verbose_name_plural = 'Запросы'


class Type(Model):
    name = CharField(max_length=10, unique=True)


class Vacancy(IsActiveMixin):
    published = DateTimeField()
    name = CharField(max_length=50)
    url = URLField()
    word_id = ForeignKey(Word, on_delete=models.CASCADE)
    area = ForeignKey(Area, on_delete=models.CASCADE)
    schedule = ForeignKey(Schedule, on_delete=models.CASCADE)
    snippet = TextField()
    salaryFrom = FloatField(default=0)
    salaryTo = FloatField(default=0)
    employer = ForeignKey(Employer, on_delete=models.CASCADE)
    type = ForeignKey(Type, on_delete=models.CASCADE)


class Skill(Model):
    name = CharField(max_length=50, verbose_name='Навык')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Название навыка'
        verbose_name_plural = 'Навыки'


class Wordskill(Model):
    id_word = ForeignKey(Word, on_delete=models.CASCADE)
    id_skill = ForeignKey(Skill, on_delete=models.CASCADE)
    count = FloatField()
    percent = FloatField()

HH/hhapp/forms.py
from django import forms
from django.forms import BaseFormSet

from hhapp.models import Area, Schedule


class ReqForm(forms.Form):
    vacancy = forms.CharField(label='Строка поиска ', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                    'placeholder': 'Введите вакансию'}))
    where = forms.ChoiceField(label='Где искать ', choices=[('all', "Везде"),
                                                            ('company', 'В названии компании'),
                                                            ('name', 'В названии вакансии')],
                              widget=forms.Select(attrs={'class': 'form-control'}))
    pages = forms.IntegerField(label='Количество анализируемых страниц ', initial=3,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))


class UserReqForm(forms.Form):
    vacancy = forms.CharField(label='Строка поиска ', widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                    'placeholder': 'Введите вакансию'}))
    where = forms.ChoiceField(label='Где искать ', choices=[('all', "Везде"),
                                                            ('company', 'В названии компании'),
                                                            ('name', 'В названии вакансии')],
                              widget=forms.Select(attrs={'class': 'form-control'}))
    pages = forms.IntegerField(label='Количество анализируемых страниц ', initial=3,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))


class AuthUserReqForm(UserReqForm):
    areas = forms.ModelMultipleChoiceField(queryset=Area.objects.all(),
                                           widget=forms.CheckboxSelectMultiple(
                                               attrs={'class': 'form-check-inline'}), label='Регион')
    schedules = forms.ModelMultipleChoiceField(queryset=Schedule.objects.all(),
                                               widget=forms.CheckboxSelectMultiple(
                                                   attrs={'class': 'form-check-inline'}), label='Занятость')

HH/hhapp/views.py
import os

from requests import get
from dotenv import load_dotenv
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import ContextMixin
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from .forms import ReqForm, UserReqForm, AuthUserReqForm
from .models import Vacancy, Word, Wordskill, Area, Schedule
from hhapp.management.commands.full_db import Command


load_dotenv()


def start(request):
    title = 'главная страница'
    return render(request, 'hhapp/index.html', {'title': title})


def form(request):
    if not request.user.is_authenticated:
        form1 = UserReqForm()
    else:
        form1 = AuthUserReqForm(initial={'vacancy': request.user.text,
                                         'areas': request.user.areas.all(),
                                         'schedules': request.user.schedules.all()})
        title = 'страница формы'
    return render(request, 'hhapp/form.html', context={'form': form1, 'title': title})


def result(request):
    print('gist')
    if request.method == 'POST':
        print('='*70)
        print('post')
        form = UserReqForm(request.POST)
        if form.is_valid():
            vac = form.cleaned_data['vacancy']
            where = form.cleaned_data['where']
            pages = form.cleaned_data['pages']
            # print(request.POST.getlist('areas'), request.POST.getlist('schedules'))

            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            # areas = [Area.objects.filter(id=it).first() for it in request.POST.getlist('areas')]
            # schedules = [Schedule.objects.filter(id=it).first() for it in request.POST.getlist('schedules')]
            # # print(areas, schedules, sep='\n')
            #~~~~~~~~~~~~~~~~~~~~~~~~
            areas_ids = request.POST.getlist('areas')
            schedules_ids = request.POST.getlist('schedules')
            # Загрузка связанных объектов с помощью select_related
            areas = Area.objects.filter(id__in=areas_ids).prefetch_related('vacancies')
            schedules = Schedule.objects.filter(id__in=schedules_ids).prefetch_related('vacancies')
            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

            #~~~~~~~~~~~~~~~~~~~~~~~~
            com = Command(vac, pages, where, areas, schedules)
            com.handle()
            v = Word.objects.get(word=vac)
            s = Wordskill.objects.filter(id_word_id=v.id).order_by('-percent').all()

            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            #~~~~~~~~~~~~~~~~~~~~~~~~
            # vac = Vacancy.active_objects.filter(word_id=v,
            #                                     area__in=areas,
            #                                     schedule__in=schedules).order_by('published').all()
            # vac = Vacancy.active_objects.all()
            #~~~~~~~~~~~~~~~~~~~~~~~~
            # Используем select_related для загрузки связанных объектов
            # vac = Vacancy.active_objects.select_related('area', 'schedule')
            vac = Vacancy.active_objects.filter(word_id=v).select_related('area', 'schedule')
            #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            
            #~~~~~~~~~~~~~~~~~~~~~~~~
            print('-'*70)
            # print(vac, v, s, sep='\n')
            print(f'Word-v: {v}')
            # print(f'Wordskill-s: {s}')
            # print(f'Vacancy-vac: {vac}')
            print(f'Total vacancies: {vac.count()}')
            #~~~~~~~~~~~~~~~~~~~~~~~~
            print('-'*70)
            paginator = Paginator(vac, 10)
            # page_number = request.GET.get('page')
            page_number = request.GET.get('page', 1)  # Устанавливаем значение по умолчанию на 1
            # print(f'page_number:{page_number}')    
            page_obj = paginator.get_page(page_number)
            print(f'page_obj: len: {len(page_obj)}')    
            print('='*70)
            return render(request, 'hhapp/about.html', context={'word': v,
                                                                'skills': s,
                                                                'page_obj': page_obj})
            #~~~~~~~~~~~~~~~~~~~~~~~~
        else:
            page_number = request.GET.get('page')
            print('get', page_number)
            if page_number:
                vac = form.cleaned_data['vacancy']
                where = form.cleaned_data['where']
                pages = form.cleaned_data['pages']
                # print(request.POST.getlist('areas'), request.POST.getlist('schedules'))
                areas = [Area.objects.filter(id=it).first() for it in request.POST.getlist('areas')]
                schedules = [Schedule.objects.filter(id=it).first() for it in request.POST.getlist('schedules')]
                v = Word.objects.get(word=vac)
                s = Wordskill.objects.filter(id_word_id=v.id).all()
                vac = Vacancy.objects.filter(word_id=v, area__in=areas, schedule__in=schedules).order_by('published').all()
                paginator = Paginator(vac, 10)
                page_obj = paginator.get_page(page_number)
                return render(request, 'hhapp/about.html', context={'word': v,
                                                                    'skills': s,
                                                                    'page_obj': page_obj})
            else:
                form1 = UserReqForm()
                return render(request, 'hhapp/form.html', context={'form': form1})


class WSList(ListView):
    model = Wordskill
    template_name = 'hhapp/ws_list.html'


class AreaList(ListView):
    model = Area
    template_name = 'hhapp/area_list.html'
    paginate_by = 3

    def get_queryset(self):
        return Area.objects.order_by('name').all()


class AreaDetail(DetailView):
    model = Area
    template_name = 'hhapp/area_detail.html'


class AreaPostMixin(ContextMixin):
    def prepare_area(self, url, areas):
        for item in areas:
            # print(item)
            if item['areas'] is not None:
                url[item['name']] = item['id']
                # print(1)
                self.prepare_area(url, item['areas'])
            else:
                url[item['name']] = item['id']

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # def parce(self, area):
    #     # r = {'url': 'https://api.superjob.ru/2.0/vacancies/',
    #     #      'param': {'town': area,
    #     #                'period': 1},
    #     #      'header': {'X-Api-App-Id': os.getenv('key_super'),
    #     #                 'Authorization': 'Bearer r.000000010000001.example.access_token',
    #     #                 'Content-Type': 'application/x-www-form-urlencoded'}
    #     #      }
    #     self.hh, self.zarpl = dict(), dict()
    #     for url, d in (('https://api.hh.ru/areas', self.hh), ('https://api.zarplata.ru/areas', self.zarpl)):
    #         res = get(url).json()
    #         self.prepare_area(d, res)
    #     # res = get(r['url'], headers=r['header'], params=r['param']).json()
    #     return {'name': area, 'ind_hh': self.hh.get(area, 0),
    #             'ind_zarp': self.zarpl.get(area, 0)}#,
    #             # 'ind_super': res['objects'][0]['town']['id'] if res['objects'] else 0}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    def parce(self, area):
        # Инициализация словарей для хранения данных
        self.hh, self.zarpl = {}, {}

        # Словарь с URL-адресами API
        api_urls = {
            'hh': 'https://api.hh.ru/areas',
            'zarpl': 'https://api.zarplata.ru/areas'
        }

        # Запросы к API для получения областей
        for key, url in api_urls.items():
            res = get(url).json()
            self.prepare_area(self.hh if key == 'hh' else self.zarpl, res)

        # Возврат результатов
        return {
            'name': area,
            'ind_hh': self.hh.get(area, 0),
            'ind_zarp': self.zarpl.get(area, 0)
        }
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    def post(self, request, *args, **kwargs):
        text = request.POST['name']
        print(text)
        new_index = self.parce(text)
        print(new_index)
        Area.objects.create(**new_index)
        return render(request, 'hhapp/area_list.html', context={'object_list': Area.objects.order_by('name').all()})


class AreaCreate(LoginRequiredMixin, CreateView, AreaPostMixin):
    model = Area
    fields = ['name']
    success_url = reverse_lazy('hh:area_list')
    template_name = 'hhapp/area_create.html'


class AreaUpdateView(UpdateView):
    model = Area
    fields = ['name']
    success_url = reverse_lazy('hhapp:area_list')
    template_name = 'hhapp/area_create.html'


class AreaDeleteView(DeleteView):
    model = Area
    success_url = reverse_lazy('hhapp:area_list')
    template_name = 'hhapp/area_delete_confirm.html'

HH/hhapp/templates/hhapp/about.html
{% extends 'base.html' %}

{% block title %}Результаты запроса{% endblock %}

{% block head %}Результаты{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section about-heading">
        <div class="container">
            <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'assets/img/about.jpg' %}" alt="..." />
            <div class="about-heading-content">
                <div class="row">
                    <div class="col-xl-15 col-lg-6 mx-auto">
                        <div class="bg-faded rounded p-5">
                            <h2 class="section-heading mb-4">
                                Результаты запроса
                            </h2>
                            <h3 class="section-heading">Параметры</h3>
                                <ol class="list-group">
                                    <li class="list-group-item" >Вакансия: {{ word.word }}</li>
                                    <li class="list-group-item">Ср. верхняя граница: {{ word.up }}руб.</li>
                                    <li class="list-group-item">Ср. нижняя граница: {{ word.down }}руб.</li>
                                </ol>
                                <table class="table">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">Номер</th>
                                            <th scope="col">Название</th>
                                            <th scope="col">Процент упоминаний</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in skills %}
                                            <tr>
                                                <th scope="row">{{ forloop.counter }} </th>
                                                <td>{{ item.id_skill.name|capfirst }}</td>
                                                <td align="right">{{ item.percent }}%</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                        </div>
                    </div>
                        <div class="col-xl-15 col-lg-10 mx-auto">
                            <div class="bg-faded rounded p-5">
                                {% for item in page_obj %}
                                    <div>
                                        <p>Дата публикации: {{ item.published }}</p>
                                        <p>Название: {{ item.name }}</p>
                                        <a href="{{ item.url }}">Ссылка</a>
                                        <p>Текст запроса: {{ item.word_id.word }}</p>
                                        <p>Регион: {{ item.area.name}}</p>
                                        <p>Занятость: {{ item.schedule.name }}</p>
                                        <p>Описание: {{ item.snippet|safe }}</p>
                                        <p>Нижняя граница: {{ item.salaryFrom }}</p>
                                        <p>Верхняя граница: {{ item.salaryTo }}</p>
                                        <p>Работодатель: {{ item.employer.name }}</p>
                                        <img src="{{ item.employer.link }}" alt="Upsss..." width="200" hight="300">
                                        <hr>
                                    </div>
                                {% endfor %}

                                <div class="pagination">
                                    <span class="step-links">
                                        {% if page_obj.has_previous %}
                                            <a href="?page=1">&laquo; first</a>
                                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                        {% endif %}

                                        <span class="current">
                                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                        </span>

                                        {% if page_obj.has_next %}
                                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                        {% endif %}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Любишь кататься - люби и саночки возить{% endblock %}

HH/hhapp/templates/hhapp/area_create.html
{% extends 'base.html' %}

{% block title %} Регионы {% endblock %}

{% block head %}Новый регион{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/412022.jpg' %}" alt="...">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Привет, привет - от больших штиблет{% endblock%}

HH/hhapp/templates/hhapp/area_delete_confirm.html
{% extends 'base.html' %}

{% block title %} Регионы {% endblock %}

{% block head %}Удаление{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/412022.jpg' %}" alt="...">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <dl>
                        <dt>{{ object.name }}</dt>
                            <dd>Индекс для hh.ru: {{ object.ind_hh }}</dd>
                            <dd>Индекс для zarp.ru: {{ object.ind_zarp }}</dd>
                            <dd>Индекс для superjob.ru: {{ object.ind_super }}</dd>
                    </dl>
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы уверены? <button type="submit" class="btn btn-danger">Да</button></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Привет, привет - от больших штиблет{% endblock%}

HH/hhapp/templates/hhapp/area_detail.html
{% extends 'base.html' %}

{% block title %} Регионы {% endblock %}

{% block head %}Регион{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/412022.jpg' %}" alt="...">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <dl>
                        <dt>{{ object.name }}</dt>
                            <dd>Индекс для hh.ru: {{ object.ind_hh }}</dd>
                            <dd>Индекс для zarp.ru: {{ object.ind_zarp }}</dd>
                            <dd>Индекс для superjob.ru: {{ object.ind_super }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Привет, привет - от больших штиблет{% endblock%}

HH/hhapp/templates/hhapp/area_list.html
{% extends 'base.html' %}

{% block title %} Регионы {% endblock %}

{% block head %}Известные регионы{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/412022.jpg' %}" alt="...">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Номер</th>
                                <th scope="col">Название региона</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in page_obj %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="{% url 'hhapp:area_detail' pk=item.pk %}">{{ item.name.title }}</a></td>
                                    <td><a href="{% url 'hhapp:area_update' pk=item.pk %}">Изменить</a></td>
                                    <td><a href="{% url 'hhapp:area_delete' pk=item.pk %}">Удалить</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class="pagination">
                        <span class="step-links">
                            {% with paginator=page_obj.paginator %}
                                {% if page_obj.has_previous %}
                                    <a href="?page=1">&laquo; first</a>
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}

                                {% for i in paginator.get_elided_page_range %}
                                    {% if paginator.ELLIPSIS == i %}
                                        {{ i }}
                                    {% else %}
                                        <a href="?page={{ i }}"
                                           class="{% if i == page_obj.number %}sr-only{% endif %}">{{ i }}</a>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <a href="?page={{ paginator.num_pages }}">last &raquo;</a>
                                {% endif %}
                            {% endwith %}
                        </span>
                    </div>
                    <a href="{% url 'hhapp:area_create' %}">Создать</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Привет, привет - от больших штиблет{% endblock %}

HH/hhapp/templates/hhapp/form.html
{% extends 'base.html' %}

{% block title %} Поиск {% endblock %}

{% block head %}Форма для поиска{% endblock %}

{% block body %}
    {% load static %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/640915.jpg' %}" alt="...">
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <form action="{% url 'hh:result' %}" method="post">
                        <div class="form-group">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <input type="submit" value="Искать вакансию" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block footer %}Работа не волк, да прибудет с вами сила{% endblock%}

HH/hhapp/templates/hhapp/index.html
{% extends 'base.html' %}

{% block body %}
        <!-- Navigation-->
{% load static %}
<section class="page-section clearfix">
    <div class="container">
        <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static '/assets/img/intro.jpg' %}" alt="..." />
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                <h2 class="section-heading mb-4">
                    <span class="section-heading-upper">Это главная страница</span>
                </h2>
                <p class="mb-3">Парсер умеет получать вакансии с hh <br>и анализировать</p>
                <p class="mb-3">Можно задать различные параметры поиска</p>
                <div class="intro-button mx-auto">
                    <a class="btn btn-primary btn-xl" href="/form">Начать поиск!</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}