HH/HH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework import routers
from hhapp.api_views import EmployerViewSet


router = routers.DefaultRouter()
router.register(r'employeries', EmployerViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hhapp.urls', namespace='hh')),
    path('users/', include('userapp.urls', namespace='users')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

HH/hhapp/urls.py
from django.urls import path
from hhapp import views


app_name = 'hhapp'

urlpatterns = [
    path('', views.start, name='index'),
    path('form/', views.form, name='form'),
    path('result/', views.result, name='result'),
    path('ws-list/', views.WSList.as_view(), name='ws_list'),
    path('area-list/', views.AreaList.as_view(), name='area_list'),
    path('area-detail/<int:pk>/', views.AreaDetail.as_view(), name='area_detail'),
    path('area-create/', views.AreaCreate.as_view(), name='area_create'),
    path('area-update/<int:pk>/', views.AreaUpdateView.as_view(), name='area_update'),
    path('area-delete/<int:pk>/', views.AreaDeleteView.as_view(), name='area_delete')
]

HH/userapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from userapp import views


app_name = 'userapp'

urlpatterns = [
    path('registration/', views.UserCreateView.as_view(), name='regist'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

HH/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load str_extensions %}
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Парсер HH{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static '/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static '/css/styles.css' %}" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="site-heading-upper text-primary mb-3">{% block head %}Мегапарсер HeadHunter{% endblock %}</span>
            </h1>
        </header>
        <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
            <div class="container">
                <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'hh:index' %}">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase" href="{% url 'hh:index' %}">Главная</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase" href="{% url 'hh:form' %}">Поиск</a>
                        </li>
                        <li class="nav-item px-lg-4">
                            <a class="nav-link text-uppercase" href="{% url 'hh:area_list' %}">Регионы</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item px-lg-4">
                                <small class="barge bg-light">
                                    Привет, {{ user.username }}
                                </small>
                                <a class="nav-link text-uppercase" href="{% url 'users:logout' %}">Выход</a>
                            </li>
                        {% else %}
                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase" href="{% url 'users:regist' %}">Регистрация</a>
                            </li>
                            <li class="nav-item px-lg-4">
                                <a class="nav-link text-uppercase" href="{% url 'users:login' %}">Вход</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}{% endblock %}
        <footer class="footer text-faded text-center py-5">
            <p>{{ title|vowelsDOWN }} </p>
            <div class="container"><p class="m-0 small">{% block footer %}Copyright &copy; Your Website 2024{% endblock %}</p></div>

            <hr>
            <p class="copyright text-muted">
                <button type="button" id="btn-joke" class="btn-info">
                Кофе или чай?
            </button>
            </p>

        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- My JS-->
        <script src="{% static 'js/my.js' %}"></script>
    </body>
</html>